// Dummy content for the "For You" page. Each user-selected interest expands
// into a handful of tiles. Eventually these will be generated by an LLM +
// web search keyed on the user's city; today, six popular interests have
// curated examples and everything else uses generic search-link tiles.
//
// The page bucket-sorts items into three sections:
//   - Upcoming events  (type: "event" | "class")
//   - Organizations    (type: "organization")
//   - Resources        (type: "community" | "resource")

export type ForYouItemType =
  | "organization"
  | "event"
  | "community"
  | "class"
  | "resource";

export type ForYouSection = "events" | "organizations" | "resources";

export type ForYouItem = {
  id: string;
  title: string;
  type: ForYouItemType;
  icon: string;
  shortDescription: string;
  longDescription: string;
  date?: string;      // e.g. "Every Saturday 9am" or "March 15, 7pm" — events only
  links: { label: string; url: string }[];
  meta?: {
    cost?: string;
    schedule?: string;
    location?: string;
  };
};

const TYPE_LABELS: Record<ForYouItemType, string> = {
  organization: "Organization",
  event: "Event",
  community: "Community",
  class: "Class",
  resource: "Resource",
};

export function getTypeLabel(t: ForYouItemType): string {
  return TYPE_LABELS[t];
}

export function sectionForType(type: ForYouItemType): ForYouSection {
  if (type === "event" || type === "class") return "events";
  if (type === "organization") return "organizations";
  return "resources";
}

const CURATED: Record<string, ForYouItem[]> = {
  climbing: [
    {
      id: "climb-bouldering-project",
      title: "Local Bouldering Gym",
      type: "organization",
      icon: "🧗",
      shortDescription: "Member-owned bouldering with a built-in community",
      longDescription:
        "Most cities have one or two flagship bouldering gyms — Bouldering Project (Austin/Seattle/Brooklyn), Brooklyn Boulders, Crux, MetroRock. Day passes are usually $20–25; memberships $80–110/month. The community forms around the route-setting cycle: new routes drop every 2–3 weeks and regulars come out to climb them together.",
      links: [
        {
          label: "Find a gym near you",
          url: "https://www.google.com/maps/search/bouldering+gym",
        },
      ],
      meta: { cost: "$20–25/day · $80–110/mo" },
    },
    {
      id: "climb-intro-class",
      title: "Beginner climbing class",
      type: "event",
      icon: "📚",
      shortDescription: "Learn the basics with a guided session",
      longDescription:
        "Almost every climbing gym runs a 90-minute Intro to Climbing class for $25–50 that teaches you knots, belaying, falling, and basic technique. Going to one is the fastest way to feel comfortable showing up alone afterward.",
      date: "Sundays at 11am",
      links: [
        {
          label: "Look up local intro classes",
          url: "https://www.google.com/search?q=beginner+climbing+class+near+me",
        },
      ],
      meta: { cost: "$25–50" },
    },
    {
      id: "climb-saturday-meetup",
      title: "Saturday outdoor climbing meetup",
      type: "event",
      icon: "🏔️",
      shortDescription: "Carpool to nearby crags, beginner-friendly",
      longDescription:
        "Most cities have a recurring outdoor climbing meetup — climbers meet at the gym Saturday morning, carpool to a nearby crag, climb together until early afternoon. Free, open to beginners with a top-rope belay cert.",
      date: "Saturdays 9am",
      links: [
        {
          label: "Find one on Meetup",
          url: "https://www.meetup.com/find/?keywords=outdoor+climbing",
        },
      ],
      meta: { cost: "Free (gas + day fees)" },
    },
    {
      id: "climb-meetup-group",
      title: "Local climbing club",
      type: "organization",
      icon: "🤝",
      shortDescription: "Recurring indoor + outdoor community",
      longDescription:
        "Most cities have an active climbing club that organizes weekly indoor sessions, monthly outdoor trips, and yearly competitions. Annual membership is usually $30–60 and includes discounts at partner gyms.",
      links: [
        {
          label: "Search Meetup",
          url: "https://www.meetup.com/find/?keywords=climbing+club",
        },
      ],
    },
    {
      id: "climb-mountain-project",
      title: "Mountain Project",
      type: "resource",
      icon: "🗺️",
      shortDescription: "Crowd-sourced outdoor climbing guidebook",
      longDescription:
        "Free guidebook to every outdoor climbing area in North America. Route descriptions, ratings, photos, conditions, and trip reports. Critical for finding outdoor climbing partners — many areas have busy forums where you can post 'looking for partner this weekend'.",
      links: [
        { label: "Mountain Project", url: "https://www.mountainproject.com/" },
      ],
    },
    {
      id: "climb-r-climbing",
      title: "r/climbing on Reddit",
      type: "community",
      icon: "💬",
      shortDescription: "Active online community for technique, gear, partners",
      longDescription:
        "1M+ members. Weekly partner-search threads by region, gear questions answered same-day, training advice, and a culture of welcoming new climbers. The pinned posts contain most of what a beginner needs.",
      links: [{ label: "r/climbing", url: "https://www.reddit.com/r/climbing/" }],
    },
  ],

  coffee: [
    {
      id: "coffee-cupping",
      title: "Public cuppings at a local roaster",
      type: "event",
      icon: "🥄",
      shortDescription: "Free coffee tastings, beginner welcome",
      longDescription:
        "Many local roasters host free or low-cost public cuppings where staff brew several origins side-by-side and walk you through how to taste. Even total beginners welcome. It's both a learning event and an easy social one.",
      date: "Saturdays 10am",
      links: [
        {
          label: "Search 'public cupping' + your city",
          url: "https://www.google.com/search?q=public+coffee+cupping+near+me",
        },
      ],
      meta: { cost: "Free–$10" },
    },
    {
      id: "coffee-latte-art",
      title: "Latte art workshop",
      type: "event",
      icon: "🎨",
      shortDescription: "2-hour beginner barista class",
      longDescription:
        "Many specialty cafes offer 2-hour latte art workshops on weekends for $50–80. You leave with hearts, rosettas, and a real understanding of milk steaming. Sociable, low pressure, you get to take home what you made.",
      date: "Weekends, varies by cafe",
      links: [
        {
          label: "Find a workshop",
          url: "https://www.google.com/search?q=latte+art+class+near+me",
        },
      ],
      meta: { cost: "$50–80" },
    },
    {
      id: "coffee-roaster-cafe",
      title: "Independent local roaster",
      type: "organization",
      icon: "☕",
      shortDescription: "Single-origin specialty coffee + community",
      longDescription:
        "Most cities have 5–15 independent roasters worth visiting. They tend to run cuppings, workshops, and community events. Becoming a regular at one specialty roaster is a great anchor — staff get to know you, you learn coffee, you meet other regulars.",
      links: [
        {
          label: "Sprudge city guides",
          url: "https://sprudge.com/category/coffee-guides",
        },
      ],
    },
    {
      id: "coffee-r-coffee",
      title: "r/coffee on Reddit",
      type: "community",
      icon: "💬",
      shortDescription: "Brewing tips, gear, and local recs",
      longDescription:
        "Largest English-language coffee community. The 'beginner brewing' wiki is excellent; weekly 'cafe of the week' threads surface independent shops worldwide.",
      links: [{ label: "r/coffee", url: "https://www.reddit.com/r/coffee/" }],
    },
  ],

  books: [
    {
      id: "books-author-reading",
      title: "Author reading at indie bookstore",
      type: "event",
      icon: "📖",
      shortDescription: "Live readings + Q&A, usually free",
      longDescription:
        "Indie bookstores host author readings 1–2 times per month, mostly free. You get the author talking about the book, a Q&A, and a small audience of other readers nearby afterwards. Lowest-stakes possible literary social event.",
      date: "Monthly, varies by bookstore",
      links: [
        {
          label: "Find indie bookstore events",
          url: "https://www.indiebound.org/indie-store-finder",
        },
      ],
      meta: { cost: "Free" },
    },
    {
      id: "books-library-events",
      title: "Public library events",
      type: "event",
      icon: "📚",
      shortDescription: "Talks, workshops, book clubs at your local library",
      longDescription:
        "Most public library systems run dozens of events monthly — author talks, writing workshops, kids' programs, language exchanges, computer classes. All free. Sign up for the events newsletter to see what's coming up.",
      date: "Multiple per week",
      links: [
        {
          label: "Find your library calendar",
          url: "https://www.google.com/search?q=public+library+events+near+me",
        },
      ],
      meta: { cost: "Free" },
    },
    {
      id: "books-indie-bookstore",
      title: "Independent bookstore",
      type: "organization",
      icon: "🏪",
      shortDescription: "Local hub for book lovers",
      longDescription:
        "Pick one indie bookstore as 'yours' and sign up for their events newsletter. Buying books there supports a real local business and tunes you into the literary scene of your city — staff picks, author visits, book launch parties.",
      links: [
        {
          label: "Find indie bookstores nearby",
          url: "https://www.indiebound.org/indie-store-finder",
        },
      ],
    },
    {
      id: "books-meetup-book-clubs",
      title: "Local book club",
      type: "organization",
      icon: "🤝",
      shortDescription: "Monthly reading + discussion groups",
      longDescription:
        "Most cities have 5–20 active book clubs on Meetup spanning genres (fiction, non-fiction, sci-fi, classics, queer lit, etc.). Most meet monthly at a coffee shop or bar. Low-stakes way to read more and meet readers.",
      links: [
        {
          label: "Search Meetup for book clubs",
          url: "https://www.meetup.com/find/?keywords=book+club",
        },
      ],
    },
    {
      id: "books-storygraph",
      title: "The StoryGraph",
      type: "resource",
      icon: "📊",
      shortDescription: "Reading tracker that recommends what to read next",
      longDescription:
        "Indie alternative to Goodreads, with better mood/pace-based recommendations and reading challenges. Free. Easy way to build a personal to-read list before your next library visit.",
      links: [{ label: "StoryGraph", url: "https://www.thestorygraph.com/" }],
    },
  ],

  running: [
    {
      id: "running-november-project",
      title: "November Project workout",
      type: "event",
      icon: "🏃",
      shortDescription: "Free outdoor group workout, no signup",
      longDescription:
        "Worldwide free fitness community that meets at 6:25am on Wednesdays + Fridays in parks and on stadium steps. No signup, no fees — just show up. Famously welcoming to total beginners. The 'tribe' culture makes it a real friend-making engine for many people.",
      date: "Wed + Fri 6:25am",
      links: [
        { label: "November Project", url: "https://november-project.com/" },
      ],
      meta: { cost: "Free" },
    },
    {
      id: "running-parkrun",
      title: "parkrun (weekly 5K)",
      type: "event",
      icon: "🌳",
      shortDescription: "Free timed 5K every Saturday",
      longDescription:
        "Volunteer-organized free 5K every Saturday at 9am in local parks. Timed, friendly, all paces welcome — many people walk it. Active in 22 countries. Show up, register once online, scan your barcode, run.",
      date: "Saturdays 9am",
      links: [{ label: "parkrun", url: "https://www.parkrun.com/" }],
      meta: { cost: "Free" },
    },
    {
      id: "running-brewery-run",
      title: "Brewery run club",
      type: "event",
      icon: "🍺",
      shortDescription: "Casual 5K then beer",
      longDescription:
        "Lots of breweries host a weekly group run (usually Mondays or Wednesdays at 6pm). Easy pace, 3–5 miles, no commitment, drink afterward. Easiest way to meet runners who aren't training for anything specific.",
      date: "Mon or Wed 6pm",
      links: [
        {
          label: "Search 'brewery run club + your city'",
          url: "https://www.google.com/search?q=brewery+run+club+near+me",
        },
      ],
    },
    {
      id: "running-local-club",
      title: "Local running club",
      type: "organization",
      icon: "📍",
      shortDescription: "Year-round community with weekly runs + training",
      longDescription:
        "Most cities have an established running club ($30–60/year membership) that organizes group runs 2–4 times a week, training groups for races, social events, and discounts at local running stores. The fastest path into the local running scene.",
      links: [
        { label: "Find clubs on Strava", url: "https://www.strava.com/clubs/search" },
      ],
    },
    {
      id: "running-marathon-training",
      title: "Marathon training group",
      type: "organization",
      icon: "🏅",
      shortDescription: "Structured 16+ week program",
      longDescription:
        "Running stores and clubs run formal marathon training groups (often $100–250 for the full program) that meet 2–3x per week for the buildup. Even if you're not committed to a marathon, the structure and built-in community make it easier to stick with running.",
      links: [
        {
          label: "Find a local running store",
          url: "https://www.google.com/maps/search/running+store",
        },
      ],
    },
    {
      id: "running-strava",
      title: "Strava local groups",
      type: "resource",
      icon: "📱",
      shortDescription: "App-based local club directory",
      longDescription:
        "Strava maintains a directory of local running clubs. Search by city, see when they meet, scan their recent activities. Most clubs use Strava to post weekly runs.",
      links: [{ label: "Strava clubs", url: "https://www.strava.com/clubs/search" }],
    },
  ],

  yoga: [
    {
      id: "yoga-park-free",
      title: "Free outdoor yoga",
      type: "event",
      icon: "🌞",
      shortDescription: "Summer park yoga, donation based",
      longDescription:
        "Most cities have at least one free outdoor yoga series in the summer — Lululemon often runs these, as do parks departments and some studios as outreach. Casual, donation-based, BYO mat.",
      date: "Saturdays 10am (summer)",
      links: [
        {
          label: "Search 'free yoga + your city'",
          url: "https://www.google.com/search?q=free+yoga+in+the+park+near+me",
        },
      ],
      meta: { cost: "Free / donation" },
    },
    {
      id: "yoga-studio-trial",
      title: "Studio intro week",
      type: "event",
      icon: "🧘",
      shortDescription: "$20–40 unlimited yoga for new students",
      longDescription:
        "Most studios offer a steeply discounted intro pack ($20–40 for 1–2 weeks unlimited) for new students. Use these to try 3–4 different studios in your first month and pick the one whose schedule, teachers, and vibe actually fit you.",
      date: "Anytime in your first 60 days",
      links: [
        { label: "ClassPass studios", url: "https://classpass.com/" },
        {
          label: "Mindbody studio search",
          url: "https://www.mindbodyonline.com/",
        },
      ],
      meta: { cost: "$20–40 intro" },
    },
    {
      id: "yoga-studio",
      title: "Local yoga studio",
      type: "organization",
      icon: "🪷",
      shortDescription: "Recurring classes + community",
      longDescription:
        "Pick one studio as your 'home base' after trying a few. Most studios have memberships ($120–180/mo unlimited) plus drop-in classes ($20–25). Becoming a regular at a single studio is one of the fastest ways to recognize the same faces week after week.",
      links: [
        {
          label: "Search nearby studios",
          url: "https://www.google.com/maps/search/yoga+studio",
        },
      ],
    },
    {
      id: "yoga-teacher-training",
      title: "200-hour teacher training",
      type: "class",
      icon: "📚",
      shortDescription: "Deep-dive program, often life-shifting",
      longDescription:
        "If you've been practicing 1+ year, a 200-hour YTT (typically over 4–6 months, $2,500–5,000) is one of the more transformative things many people do. Even people who don't end up teaching come away with strong friendships and a much deeper practice.",
      date: "Multi-month cohorts",
      links: [
        {
          label: "Yoga Alliance directory",
          url: "https://www.yogaalliance.org/Directory",
        },
      ],
    },
    {
      id: "yoga-doyogawithme",
      title: "DoYogaWithMe",
      type: "resource",
      icon: "💻",
      shortDescription: "Free, high-quality online classes",
      longDescription:
        "Hundreds of free full-length classes from experienced teachers, filterable by length, level, and style. Great for solo practice between studio visits, or if you can't afford studio prices right away.",
      links: [
        { label: "DoYogaWithMe", url: "https://www.doyogawithme.com/" },
      ],
    },
  ],

  volunteering: [
    {
      id: "vol-food-bank-shift",
      title: "Weekly food bank shift",
      type: "event",
      icon: "🥫",
      shortDescription: "Recurring 2–3 hour volunteer slot",
      longDescription:
        "Food banks typically run weekly volunteer shifts — sorting donations, packing boxes, distributing food. Easy to commit to, mostly the same people week to week, conversations happen naturally. Sign up online, just show up.",
      date: "Weekly, usually Sat or Wed",
      links: [
        {
          label: "Find a food bank",
          url: "https://www.feedingamerica.org/find-your-local-foodbank",
        },
      ],
      meta: { cost: "Free", schedule: "2–3 hour shifts" },
    },
    {
      id: "vol-habitat-build",
      title: "Habitat for Humanity build day",
      type: "event",
      icon: "🔨",
      shortDescription: "Weekend house-building with 10–20 volunteers",
      longDescription:
        "Most Habitat chapters host weekend build days where 10–20 volunteers work on a house together. No construction experience needed — supervisors show you what to do. Strong social vibes since you're doing physical work alongside other volunteers for several hours.",
      date: "Saturdays 8am–2pm",
      links: [
        { label: "Find a chapter", url: "https://www.habitat.org/local" },
      ],
      meta: { cost: "Free" },
    },
    {
      id: "vol-food-bank",
      title: "Local food bank",
      type: "organization",
      icon: "🥬",
      shortDescription: "Hunger-relief nonprofit",
      longDescription:
        "Every region has a major food bank (often a Feeding America affiliate). Long-term volunteer roles include shift leader, driver, intake coordinator, and warehouse manager. Great for building serious local connections over months.",
      links: [
        {
          label: "Find a food bank",
          url: "https://www.feedingamerica.org/find-your-local-foodbank",
        },
      ],
    },
    {
      id: "vol-animal-shelter",
      title: "Animal shelter",
      type: "organization",
      icon: "🐕",
      shortDescription: "Walk dogs, socialize cats, foster",
      longDescription:
        "Most shelters need ongoing volunteer dog-walkers and cat-socializers. A 2-hour shift 1–2 times per week is typical. Particularly good for people who like animals but can't commit to a pet yet.",
      links: [
        {
          label: "Find a shelter",
          url: "https://resources.bestfriends.org/local-shelter",
        },
      ],
    },
    {
      id: "vol-volunteer-match",
      title: "VolunteerMatch",
      type: "resource",
      icon: "🤝",
      shortDescription: "Searchable database of opportunities",
      longDescription:
        "Search by cause, distance, and skills. The largest and most-active opportunity database. Filter for 'good for groups' if you want something to do with friends, or 'virtual' if you can't get out yet.",
      links: [
        { label: "VolunteerMatch", url: "https://www.volunteermatch.org/" },
      ],
    },
  ],
};

function genericFallback(interest: string): ForYouItem[] {
  const enc = encodeURIComponent(interest);
  return [
    {
      id: `${interest}-luma-eventbrite`,
      title: `${interest} events near you`,
      type: "event",
      icon: "🎟️",
      shortDescription: "Upcoming events on Luma + Eventbrite",
      longDescription: `Luma (lu.ma) is where most professional/tech/hobby events get posted these days; Eventbrite covers a broader range. Search both for one-off and recurring ${interest} events in your area.`,
      date: "Search for upcoming",
      links: [
        { label: "Search Luma", url: `https://lu.ma/discover` },
        {
          label: "Search Eventbrite",
          url: `https://www.eventbrite.com/d/online/${enc}/`,
        },
      ],
    },
    {
      id: `${interest}-meetup`,
      title: `${interest} groups on Meetup`,
      type: "organization",
      icon: "🤝",
      shortDescription: "Recurring groups to join",
      longDescription: `Meetup hosts groups for almost every interest. Search by your interest plus your city to find local recurring meetups — most are free or under $10 and meet 1–4 times per month.`,
      links: [
        {
          label: "Search Meetup",
          url: `https://www.meetup.com/find/?keywords=${enc}`,
        },
      ],
    },
    {
      id: `${interest}-reddit`,
      title: `${interest} on Reddit`,
      type: "community",
      icon: "💬",
      shortDescription: "Subreddits + your city subreddit",
      longDescription: `Two places: a subreddit dedicated to your interest (e.g. r/${interest.replace(/\s+/g, "").toLowerCase()}), and your local city subreddit where you can post asking for recommendations.`,
      links: [
        {
          label: "Search Reddit",
          url: `https://www.reddit.com/search/?q=${enc}`,
        },
      ],
    },
    {
      id: `${interest}-facebook`,
      title: `${interest} Facebook Groups`,
      type: "community",
      icon: "👥",
      shortDescription: "Local online community groups",
      longDescription: `Even if you don't use Facebook day-to-day, the Groups feature is where a lot of recurring local activity organizes — classifieds, recommendations, event invites. Worth a single login.`,
      links: [
        {
          label: "Search Facebook Groups",
          url: `https://www.facebook.com/search/groups/?q=${enc}`,
        },
      ],
    },
    {
      id: `${interest}-city-events`,
      title: "Your city's events calendar",
      type: "resource",
      icon: "🏛️",
      shortDescription: "Local government + tourism board listings",
      longDescription: `Most city governments and visitor bureaus maintain a public events calendar covering everything from festivals to free park programs. Search for your city's official site and bookmark the events page.`,
      links: [
        {
          label: "Search for your city's events",
          url: `https://www.google.com/search?q=${enc}+events+near+me`,
        },
      ],
    },
  ];
}

export function getForYouItems(interest: string): ForYouItem[] {
  return CURATED[interest.toLowerCase()] ?? genericFallback(interest);
}
