import type { Badge, Plan, Profile, Task, UserBadge } from "./types";

export const MOCK_USER_ID = "mock-user-1";

export const mockProfile: Profile = {
  userId: MOCK_USER_ID,
  displayName: "Isabel",
  city: "Austin, TX",
  moveDate: "2026-05-01",
  socialEnergy: "medium",
  hasCar: true,
  budgetTier: "medium",
  interests: ["climbing", "coffee", "books", "running"],
  priorities: ["community", "fitness", "creative"],
};

export const mockPlan: Plan = {
  id: "plan-1",
  userId: MOCK_USER_ID,
  version: 1,
  isActive: true,
  generatedAt: "2026-05-01T00:00:00Z",
};

export const mockTasks: Task[] = [
  {
    id: "t1",
    planId: "plan-1",
    userId: MOCK_USER_ID,
    category: "routine",
    title: "Unpack one box every day this week",
    description: "Small daily wins beat one exhausting weekend.",
    dayOffset: 0,
    linkUrl: null,
    status: "pending",
    completedAt: null,
    orderIndex: 0,
    isEventAttendance: false,
    isRecurringActivity: false,
  },
  {
    id: "t2",
    planId: "plan-1",
    userId: MOCK_USER_ID,
    category: "exploration",
    title: "Walk every street within 4 blocks of home",
    description: "Map your neighborhood with your feet.",
    dayOffset: 1,
    linkUrl: null,
    status: "pending",
    completedAt: null,
    orderIndex: 0,
    isEventAttendance: false,
    isRecurringActivity: false,
  },
  {
    id: "t3",
    planId: "plan-1",
    userId: MOCK_USER_ID,
    category: "community",
    title: "Find a coffee shop you can become a regular at",
    description: "Pick one within walking distance and go twice this week.",
    dayOffset: 2,
    linkUrl: "https://www.google.com/maps/search/coffee+shop+near+me",
    status: "pending",
    completedAt: null,
    orderIndex: 0,
    isEventAttendance: false,
    isRecurringActivity: true,
  },
  {
    id: "t4",
    planId: "plan-1",
    userId: MOCK_USER_ID,
    category: "hobby",
    title: "Visit a local climbing gym for a day pass",
    description: "Talk to the front desk about beginner sessions and meetups.",
    dayOffset: 3,
    linkUrl: "https://www.google.com/maps/search/climbing+gym+austin",
    status: "pending",
    completedAt: null,
    orderIndex: 0,
    isEventAttendance: true,
    isRecurringActivity: false,
  },
  {
    id: "t5",
    planId: "plan-1",
    userId: MOCK_USER_ID,
    category: "community",
    title: "Search Meetup for events matching your interests",
    description: "RSVP to one before the end of the week.",
    dayOffset: 4,
    linkUrl: "https://www.meetup.com/find/?keywords=climbing&location=Austin",
    status: "pending",
    completedAt: null,
    orderIndex: 0,
    isEventAttendance: false,
    isRecurringActivity: false,
  },
  {
    id: "t6",
    planId: "plan-1",
    userId: MOCK_USER_ID,
    category: "routine",
    title: "Establish a weekly grocery run",
    description: "Pick a day and store. Consistency builds neighborhood familiarity.",
    dayOffset: 6,
    linkUrl: null,
    status: "pending",
    completedAt: null,
    orderIndex: 0,
    isEventAttendance: false,
    isRecurringActivity: true,
  },
  {
    id: "t7",
    planId: "plan-1",
    userId: MOCK_USER_ID,
    category: "hobby",
    title: "Join a running club",
    description: "Most cities have a free weekly run — find Austin's.",
    dayOffset: 8,
    linkUrl: "https://www.google.com/search?q=austin+running+club",
    status: "pending",
    completedAt: null,
    orderIndex: 0,
    isEventAttendance: false,
    isRecurringActivity: true,
  },
  {
    id: "t8",
    planId: "plan-1",
    userId: MOCK_USER_ID,
    category: "exploration",
    title: "Visit a bookstore in a neighborhood you don't live in",
    description: "Different part of town, different vibe, new mental map.",
    dayOffset: 10,
    linkUrl: null,
    status: "pending",
    completedAt: null,
    orderIndex: 0,
    isEventAttendance: false,
    isRecurringActivity: false,
  },
  {
    id: "t9",
    planId: "plan-1",
    userId: MOCK_USER_ID,
    category: "community",
    title: "Attend one Meetup event you RSVP'd to",
    description: "Stay at least 45 minutes. Talk to two people.",
    dayOffset: 12,
    linkUrl: null,
    status: "pending",
    completedAt: null,
    orderIndex: 0,
    isEventAttendance: true,
    isRecurringActivity: false,
  },
  {
    id: "t10",
    planId: "plan-1",
    userId: MOCK_USER_ID,
    category: "routine",
    title: "Set up a recurring weekly anchor",
    description: "Same time, same place every week — gym class, run club, trivia night.",
    dayOffset: 14,
    linkUrl: null,
    status: "pending",
    completedAt: null,
    orderIndex: 0,
    isEventAttendance: false,
    isRecurringActivity: true,
  },
  {
    id: "t11",
    planId: "plan-1",
    userId: MOCK_USER_ID,
    category: "exploration",
    title: "Eat at a restaurant outside your usual cuisine",
    description: "Pick something you wouldn't have tried back home.",
    dayOffset: 16,
    linkUrl: null,
    status: "pending",
    completedAt: null,
    orderIndex: 0,
    isEventAttendance: false,
    isRecurringActivity: false,
  },
  {
    id: "t12",
    planId: "plan-1",
    userId: MOCK_USER_ID,
    category: "community",
    title: "Invite one acquaintance to do something",
    description: "Coffee, a walk, anything. The ask is what counts.",
    dayOffset: 18,
    linkUrl: null,
    status: "pending",
    completedAt: null,
    orderIndex: 0,
    isEventAttendance: false,
    isRecurringActivity: false,
  },
  {
    id: "t13",
    planId: "plan-1",
    userId: MOCK_USER_ID,
    category: "hobby",
    title: "Book a beginner climbing class",
    description: "Structured learning is faster than going alone.",
    dayOffset: 20,
    linkUrl: null,
    status: "pending",
    completedAt: null,
    orderIndex: 0,
    isEventAttendance: true,
    isRecurringActivity: false,
  },
  {
    id: "t14",
    planId: "plan-1",
    userId: MOCK_USER_ID,
    category: "exploration",
    title: "Take a day trip to somewhere within an hour",
    description: "Get a feel for what's nearby beyond the city itself.",
    dayOffset: 22,
    linkUrl: null,
    status: "pending",
    completedAt: null,
    orderIndex: 0,
    isEventAttendance: false,
    isRecurringActivity: false,
  },
  {
    id: "t15",
    planId: "plan-1",
    userId: MOCK_USER_ID,
    category: "community",
    title: "Go to a recurring event for the second time",
    description: "Familiar faces start to recognize you on the second visit.",
    dayOffset: 25,
    linkUrl: null,
    status: "pending",
    completedAt: null,
    orderIndex: 0,
    isEventAttendance: true,
    isRecurringActivity: false,
  },
  {
    id: "t16",
    planId: "plan-1",
    userId: MOCK_USER_ID,
    category: "routine",
    title: "Review your month and pick one anchor to keep",
    description: "One repeatable thing is the start of a life here.",
    dayOffset: 29,
    linkUrl: null,
    status: "pending",
    completedAt: null,
    orderIndex: 0,
    isEventAttendance: false,
    isRecurringActivity: false,
  },
];

export const mockBadges: Badge[] = [
  {
    id: "b1",
    slug: "first_step",
    name: "First Step",
    description: "Complete your first task",
    icon: "🌱",
    criteria: { type: "tasks_completed", count: 1 },
  },
  {
    id: "b2",
    slug: "momentum",
    name: "Momentum",
    description: "Complete 3 tasks",
    icon: "⚡",
    criteria: { type: "tasks_completed", count: 3 },
  },
  {
    id: "b3",
    slug: "showed_up",
    name: "Showed Up",
    description: "Mark an event-attendance task complete",
    icon: "👋",
    criteria: { type: "event_attendance", count: 1 },
  },
  {
    id: "b4",
    slug: "regular",
    name: "Regular",
    description: "Complete 2 recurring-activity tasks",
    icon: "🔁",
    criteria: { type: "recurring_completed", count: 2 },
  },
  {
    id: "b5",
    slug: "newhere",
    name: "NewHere",
    description: "Complete 80% of your 30-day plan",
    icon: "🌳",
    criteria: { type: "completion_pct", pct: 80 },
  },
];

export const mockUserBadges: UserBadge[] = [];
