import type { Badge, Plan, Profile, Task, UserBadge } from "./types";

export const MOCK_USER_ID = "mock-user-1";

export const mockProfile: Profile = {
  userId: MOCK_USER_ID,
  displayName: "Isabel",
  city: "Austin, TX",
  moveDate: "2026-05-01",
  socialStyle: "ambivert",
  hasCar: true,
  budgetTier: "medium",
  interests: ["climbing", "coffee", "books", "running"],
  goals: ["Make new friends", "Build healthy habits", "Pursue a hobby or creative passion"],
};

export const mockPlan: Plan = {
  id: "plan-1",
  userId: MOCK_USER_ID,
  version: 1,
  isActive: true,
  generatedAt: "2026-05-01T00:00:00Z",
};

// 7/30/90 plan: 8 Week 1 essentials, 11 Month 1, 9 Quarter 1 (28 total)
// Meets PRD acceptance criterion: ≥5 / ≥8 / ≥8
// keeperState + sourceItemId are defaulted at insert time so the seed
// data doesn't need to repeat them on every entry.
export const mockTasks: Omit<Task, "keeperState" | "sourceItemId">[] = [
  // -------- Week 1 (days 0–6): administrative + setup essentials --------
  {
    id: "w1-license",
    planId: "plan-1",
    userId: MOCK_USER_ID,
    category: "essentials",
    phase: "week_one",
    title: "Update your driver's license, vehicle registration, and voter registration",
    description:
      "The unglamorous foundation of being a resident. Most states have online forms — start there, then book a DMV appointment if needed.",
    dayOffset: 0,
    linkUrl: null,
    status: "pending",
    completedAt: null,
    orderIndex: 0,
    isEventAttendance: false,
    isRecurringActivity: false,
  },
  {
    id: "w1-address",
    planId: "plan-1",
    userId: MOCK_USER_ID,
    category: "essentials",
    phase: "week_one",
    title: "Update your address with banks, credit cards, employer, and USPS",
    description:
      "USPS mail forwarding takes ~10 days to kick in — do this first so old mail doesn't keep piling up at your old place.",
    dayOffset: 0,
    linkUrl: null,
    status: "pending",
    completedAt: null,
    orderIndex: 1,
    isEventAttendance: false,
    isRecurringActivity: false,
  },
  {
    id: "w1-utilities",
    planId: "plan-1",
    userId: MOCK_USER_ID,
    category: "essentials",
    phase: "week_one",
    title: "Set up utilities, internet, and trash/recycling",
    description:
      "Electric, gas, water, internet. While you're at it, sign up for local emergency alerts and get renter's or home insurance in place.",
    dayOffset: 1,
    linkUrl: null,
    status: "pending",
    completedAt: null,
    orderIndex: 0,
    isEventAttendance: false,
    isRecurringActivity: false,
  },
  {
    id: "w1-library",
    planId: "plan-1",
    userId: MOCK_USER_ID,
    category: "essentials",
    phase: "week_one",
    title: "Get a library card",
    description:
      "Free books, free workspace, free events. The most underrated welcome gift any city offers a new resident.",
    dayOffset: 2,
    linkUrl: null,
    status: "pending",
    completedAt: null,
    orderIndex: 0,
    isEventAttendance: false,
    isRecurringActivity: false,
  },
  {
    id: "w1-health",
    planId: "plan-1",
    userId: MOCK_USER_ID,
    category: "essentials",
    phase: "week_one",
    title: "Find a primary care doctor, dentist, and pharmacy nearby",
    description:
      "Note your nearest urgent care too — easier to research now than to figure out at 11pm when you actually need one. Add a vet if you have pets.",
    dayOffset: 3,
    linkUrl: null,
    status: "pending",
    completedAt: null,
    orderIndex: 0,
    isEventAttendance: false,
    isRecurringActivity: false,
  },
  {
    id: "w1-transit",
    planId: "plan-1",
    userId: MOCK_USER_ID,
    category: "essentials",
    phase: "week_one",
    title: "Learn your transit options + parking rules",
    description:
      "Get a transit card or app, learn street-sweeping days, update your toll pass, and find reliable gas or charging stations. Avoid the parking-ticket surprise.",
    dayOffset: 4,
    linkUrl: null,
    status: "pending",
    completedAt: null,
    orderIndex: 0,
    isEventAttendance: false,
    isRecurringActivity: false,
  },
  {
    id: "w1-daily-shops",
    planId: "plan-1",
    userId: MOCK_USER_ID,
    category: "essentials",
    phase: "week_one",
    title: "Locate your nearest grocery, hardware store, pharmacy, and coffee shop",
    description:
      "Also flag a gym, dry cleaner, and barber or hair salon. These are the places you'll end up at again and again — easier when you know where they are.",
    dayOffset: 5,
    linkUrl: null,
    status: "pending",
    completedAt: null,
    orderIndex: 0,
    isEventAttendance: false,
    isRecurringActivity: false,
  },
  {
    id: "w1-home-safety",
    planId: "plan-1",
    userId: MOCK_USER_ID,
    category: "essentials",
    phase: "week_one",
    title: "Check smoke + CO detectors, locate water shutoff and electrical panel",
    description:
      "Make a couple of spare keys, update home security codes, and confirm trash pickup days. The stuff you'll be glad you sorted before you need it.",
    dayOffset: 6,
    linkUrl: null,
    status: "pending",
    completedAt: null,
    orderIndex: 0,
    isEventAttendance: false,
    isRecurringActivity: false,
  },

  // -------- Month 1 (days 7–29): start building habits and meeting people --------
  {
    id: "m1-coffee-regular",
    planId: "plan-1",
    userId: MOCK_USER_ID,
    category: "community",
    phase: "month_one",
    title: "Find a coffee shop you can become a regular at",
    description: "Pick one within walking distance and go twice this week. Familiarity is the start of community.",
    dayOffset: 7,
    linkUrl: "https://www.google.com/maps/search/coffee+shop+near+me",
    status: "pending",
    completedAt: null,
    orderIndex: 0,
    isEventAttendance: false,
    isRecurringActivity: true,
  },
  {
    id: "m1-grocery-routine",
    planId: "plan-1",
    userId: MOCK_USER_ID,
    category: "routine",
    phase: "month_one",
    title: "Establish a weekly grocery run",
    description: "Pick a day and store. Consistency builds neighborhood familiarity.",
    dayOffset: 8,
    linkUrl: null,
    status: "pending",
    completedAt: null,
    orderIndex: 0,
    isEventAttendance: false,
    isRecurringActivity: true,
  },
  {
    id: "m1-climbing-gym",
    planId: "plan-1",
    userId: MOCK_USER_ID,
    category: "hobby",
    phase: "month_one",
    title: "Visit a local climbing gym for a day pass",
    description: "Talk to the front desk about beginner sessions and meetups.",
    dayOffset: 10,
    linkUrl: "https://www.google.com/maps/search/climbing+gym+austin",
    status: "pending",
    completedAt: null,
    orderIndex: 0,
    isEventAttendance: true,
    isRecurringActivity: false,
  },
  {
    id: "m1-meetup-rsvp",
    planId: "plan-1",
    userId: MOCK_USER_ID,
    category: "community",
    phase: "month_one",
    title: "Search Meetup for events matching your interests and RSVP to one",
    description: "Just one event. Get it on the calendar before the week is out.",
    dayOffset: 11,
    linkUrl: "https://www.meetup.com/find/?keywords=climbing&location=Austin",
    status: "pending",
    completedAt: null,
    orderIndex: 0,
    isEventAttendance: false,
    isRecurringActivity: false,
  },
  {
    id: "m1-run-club",
    planId: "plan-1",
    userId: MOCK_USER_ID,
    category: "hobby",
    phase: "month_one",
    title: "Join a running club",
    description: "Most cities have a free weekly run — find Austin's.",
    dayOffset: 12,
    linkUrl: "https://www.google.com/search?q=austin+running+club",
    status: "pending",
    completedAt: null,
    orderIndex: 0,
    isEventAttendance: false,
    isRecurringActivity: true,
  },
  {
    id: "m1-new-bookstore",
    planId: "plan-1",
    userId: MOCK_USER_ID,
    category: "exploration",
    phase: "month_one",
    title: "Visit a bookstore in a neighborhood you don't live in",
    description: "Different part of town, different vibe, new mental map.",
    dayOffset: 14,
    linkUrl: null,
    status: "pending",
    completedAt: null,
    orderIndex: 0,
    isEventAttendance: false,
    isRecurringActivity: false,
  },
  {
    id: "m1-meetup-attend",
    planId: "plan-1",
    userId: MOCK_USER_ID,
    category: "community",
    phase: "month_one",
    title: "Attend the Meetup event you RSVP'd to",
    description: "Stay at least 45 minutes. Talk to two people.",
    dayOffset: 17,
    linkUrl: null,
    status: "pending",
    completedAt: null,
    orderIndex: 0,
    isEventAttendance: true,
    isRecurringActivity: false,
  },
  {
    id: "m1-weekly-anchor",
    planId: "plan-1",
    userId: MOCK_USER_ID,
    category: "routine",
    phase: "month_one",
    title: "Set up a recurring weekly anchor",
    description: "Same time, same place every week — class, run club, or trivia night.",
    dayOffset: 20,
    linkUrl: null,
    status: "pending",
    completedAt: null,
    orderIndex: 0,
    isEventAttendance: false,
    isRecurringActivity: true,
  },
  {
    id: "m1-new-cuisine",
    planId: "plan-1",
    userId: MOCK_USER_ID,
    category: "exploration",
    phase: "month_one",
    title: "Eat at a restaurant outside your usual cuisine",
    description: "Pick something you wouldn't have tried back home.",
    dayOffset: 23,
    linkUrl: null,
    status: "pending",
    completedAt: null,
    orderIndex: 0,
    isEventAttendance: false,
    isRecurringActivity: false,
  },
  {
    id: "m1-invite",
    planId: "plan-1",
    userId: MOCK_USER_ID,
    category: "community",
    phase: "month_one",
    title: "Invite one acquaintance to do something",
    description: "Coffee, a walk, anything. The ask is what counts.",
    dayOffset: 26,
    linkUrl: null,
    status: "pending",
    completedAt: null,
    orderIndex: 0,
    isEventAttendance: false,
    isRecurringActivity: false,
  },
  {
    id: "m1-beginner-class",
    planId: "plan-1",
    userId: MOCK_USER_ID,
    category: "hobby",
    phase: "month_one",
    title: "Book a beginner climbing class",
    description: "Structured learning is faster than going alone.",
    dayOffset: 29,
    linkUrl: null,
    status: "pending",
    completedAt: null,
    orderIndex: 0,
    isEventAttendance: true,
    isRecurringActivity: false,
  },

  // -------- Quarter 1 (days 30–89): deeper commitments and longer reach --------
  {
    id: "q1-day-trip",
    planId: "plan-1",
    userId: MOCK_USER_ID,
    category: "exploration",
    phase: "quarter_one",
    title: "Take a day trip somewhere within an hour",
    description: "Get a feel for what's nearby beyond the city itself.",
    dayOffset: 32,
    linkUrl: null,
    status: "pending",
    completedAt: null,
    orderIndex: 0,
    isEventAttendance: false,
    isRecurringActivity: false,
  },
  {
    id: "q1-host",
    planId: "plan-1",
    userId: MOCK_USER_ID,
    category: "community",
    phase: "quarter_one",
    title: "Host a small gathering of 3–5 people you've met",
    description:
      "Coffee, board games, a walk — low-stakes format. Hosting gives you a reason to invite people you've only met once.",
    dayOffset: 38,
    linkUrl: null,
    status: "pending",
    completedAt: null,
    orderIndex: 0,
    isEventAttendance: false,
    isRecurringActivity: false,
  },
  {
    id: "q1-multi-week-class",
    planId: "plan-1",
    userId: MOCK_USER_ID,
    category: "hobby",
    phase: "quarter_one",
    title: "Commit to a 4-week class or workshop",
    description: "Cooking, pottery, language — anything that meets weekly. Same group, four times in a row.",
    dayOffset: 42,
    linkUrl: null,
    status: "pending",
    completedAt: null,
    orderIndex: 0,
    isEventAttendance: true,
    isRecurringActivity: true,
  },
  {
    id: "q1-new-hood",
    planId: "plan-1",
    userId: MOCK_USER_ID,
    category: "exploration",
    phase: "quarter_one",
    title: "Visit a neighborhood you've never been to",
    description: "Eat lunch there. Walk around for an hour. Notice what's different from your own.",
    dayOffset: 48,
    linkUrl: null,
    status: "pending",
    completedAt: null,
    orderIndex: 0,
    isEventAttendance: false,
    isRecurringActivity: false,
  },
  {
    id: "q1-volunteer",
    planId: "plan-1",
    userId: MOCK_USER_ID,
    category: "community",
    phase: "quarter_one",
    title: "Volunteer at a local organization",
    description: "Volunteering is one of the highest-density ways to meet engaged locals.",
    dayOffset: 53,
    linkUrl: "https://www.volunteermatch.org/search/?l=Austin",
    status: "pending",
    completedAt: null,
    orderIndex: 0,
    isEventAttendance: true,
    isRecurringActivity: true,
  },
  {
    id: "q1-regular-partner",
    planId: "plan-1",
    userId: MOCK_USER_ID,
    category: "hobby",
    phase: "quarter_one",
    title: "Find a regular hiking or running partner",
    description: "Someone who'll text you when they're going — accountability turns intent into habit.",
    dayOffset: 60,
    linkUrl: null,
    status: "pending",
    completedAt: null,
    orderIndex: 0,
    isEventAttendance: false,
    isRecurringActivity: true,
  },
  {
    id: "q1-third-place",
    planId: "plan-1",
    userId: MOCK_USER_ID,
    category: "routine",
    phase: "quarter_one",
    title: "Identify a 'third place' that isn't home or work",
    description: "A library, gym, or coffee shop you visit weekly. By month 3, the staff should know your face.",
    dayOffset: 70,
    linkUrl: null,
    status: "pending",
    completedAt: null,
    orderIndex: 0,
    isEventAttendance: false,
    isRecurringActivity: true,
  },
  {
    id: "q1-weekend-trip",
    planId: "plan-1",
    userId: MOCK_USER_ID,
    category: "exploration",
    phase: "quarter_one",
    title: "Take a weekend trip to somewhere within 3 hours",
    description: "Get out of the city for two days. You'll come back understanding home better.",
    dayOffset: 80,
    linkUrl: null,
    status: "pending",
    completedAt: null,
    orderIndex: 0,
    isEventAttendance: false,
    isRecurringActivity: false,
  },
  {
    id: "q1-review",
    planId: "plan-1",
    userId: MOCK_USER_ID,
    category: "routine",
    phase: "quarter_one",
    title: "Review your quarter and pick three anchors to keep",
    description: "Three repeatable things you do every week is the start of a real life here.",
    dayOffset: 89,
    linkUrl: null,
    status: "pending",
    completedAt: null,
    orderIndex: 0,
    isEventAttendance: false,
    isRecurringActivity: false,
  },
];

export const mockBadges: Badge[] = [
  {
    id: "b1",
    slug: "first_step",
    name: "First Step",
    description: "Complete your first task",
    icon: "🌱",
    criteria: { type: "tasks_completed", count: 1 },
  },
  {
    id: "b2",
    slug: "momentum",
    name: "Momentum",
    description: "Complete 3 tasks",
    icon: "⚡",
    criteria: { type: "tasks_completed", count: 3 },
  },
  {
    id: "b3",
    slug: "showed_up",
    name: "Showed Up",
    description: "Mark an event-attendance task complete",
    icon: "👋",
    criteria: { type: "event_attendance", count: 1 },
  },
  {
    id: "b4",
    slug: "regular",
    name: "Regular",
    description: "Complete 2 recurring-activity tasks",
    icon: "🔁",
    criteria: { type: "recurring_completed", count: 2 },
  },
  {
    id: "b5",
    slug: "newhere",
    name: "NewHere",
    description: "Complete 80% of your plan",
    icon: "🌳",
    criteria: { type: "completion_pct", pct: 80 },
  },
];

export const mockUserBadges: UserBadge[] = [];
